services:
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:8.0
    container_name: miracle-yii-stack-mysql-1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: miracle
    volumes:
      - ./mysql_data:/var/lib/mysql
